version: '2'
services:
  tribeca:
    build:
      context: ./
    image: tribeca
    env_file:
      - ./env
    links:
      - tribeca-mongo
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - "./:/tribeca"
    tty: true
    entrypoint: /bin/sh
  tribeca-mongo:
    image: mongo
    restart: on-failure